
/**
 * Data Privacy & Anonymization Utilities
 * Implements "Privacy by Design" for AI processing.
 */

interface SensitiveData {
    id: string;
    name?: string;
    phone?: string;
    email?: string;
    [key: string]: any;
}

// 1. Anonymize User Data before AI processing
// Replaces PII with hash or generic placeholders
export const anonymizeForAI = (data: SensitiveData[]): any[] => {
    return data.map(item => {
        // Create a deep copy to protect original data
        const clean = { ...item };

        // Remove direct identifiers
        delete clean.name;
        delete clean.phone;
        delete clean.email;

        // Keep ID for mapping results back, but hashing is better in production
        // clean.id = hash(item.id); 

        return clean;
    });
};

// 2. Data Minimization
// Only sends fields strictly necessary for the specific AI task
export const minimizeForRouting = (units: any[]) => {
    return units.map(u => ({
        id: u.id,
        coordinates: u.coordinates,
        fillLevel: u.fillLevel,
        // Exclude: maintenance history, technicians name, unrelated metadata
    }));
};

// 3. AI Disclaimer Text
// Standardized explanations for AI behaviors
export const AI_DISCLAIMERS = {
    PREDICTION: "This forecast is generated by AI based on historical patterns. Actual results may vary due to weather or unforeseen events.",
    ROUTING: "Routes are optimized for distance. Local road conditions or restrictions are not fully accounted for.",
    GENERAL: "AI suggestions are for decision support only. Human oversight is required for all critical actions."
};
